#!/usr/bin/env bash

set -euo pipefail

GENERATED_NOTICE='<!-- Generated from AGENTS.md by scripts/sync-agent-config.sh. Do not edit directly. -->'
GENERATED_MARKER='.generated-by-sync-agent-config'
LEGACY_MANIFEST='.agent-config-sync.json'

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

usage() {
  printf 'Usage: %s [--check] [--root PATH]\n' "${0##*/}"
}

check_only=0
project_root=''

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check)
      check_only=1
      shift
      ;;
    --root)
      [ "$#" -ge 2 ] || die '--root requires a path'
      project_root=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

if [ -z "$project_root" ]; then
  script_dir=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
  project_root=$(CDPATH= cd -- "$script_dir/.." && pwd -P)
else
  project_root=$(CDPATH= cd -- "$project_root" && pwd -P)
fi

agents_file="$project_root/AGENTS.md"
claude_file="$project_root/CLAUDE.md"
skills_root="$project_root/skills"
agents_parent="$project_root/.agents"
claude_parent="$project_root/.claude"
agents_destination="$agents_parent/skills"
claude_destination="$claude_parent/skills"

[ -f "$agents_file" ] || die "missing canonical instructions: $agents_file"
[ -d "$skills_root" ] || die "missing canonical skills directory: $skills_root"
[ ! -L "$skills_root" ] || die "canonical skills directory cannot be a symlink: $skills_root"

validate_parent() {
  parent=$1
  if [ -L "$parent" ]; then
    die "refusing to write through symlinked directory: $parent"
  fi
  if [ -e "$parent" ] && [ ! -d "$parent" ]; then
    die "destination parent is not a directory: $parent"
  fi
}

validate_destination() {
  destination=$1
  if [ -L "$destination" ]; then
    die "destination directory cannot be a symlink: $destination"
  fi
  if [ ! -e "$destination" ]; then
    return
  fi
  [ -d "$destination" ] || die "destination is not a directory: $destination"
  if [ -f "$destination/$GENERATED_MARKER" ] ||
    [ -f "$destination/$LEGACY_MANIFEST" ]; then
    return
  fi
  first_entry=$(find "$destination" -mindepth 1 -maxdepth 1 -print -quit)
  [ -z "$first_entry" ] ||
    die "refusing to replace unmarked skill directory: $destination"
}

validate_parent "$agents_parent"
validate_parent "$claude_parent"
validate_destination "$agents_destination"
validate_destination "$claude_destination"

if [ -L "$claude_file" ]; then
  die "refusing to replace symlink: $claude_file"
fi
if [ -e "$claude_file" ] && [ ! -f "$claude_file" ]; then
  die "refusing to replace non-file path: $claude_file"
fi
if [ -f "$claude_file" ]; then
  first_line=$(sed -n '1p' "$claude_file")
  if [ "$first_line" != "$GENERATED_NOTICE" ]; then
    die "refusing to replace hand-maintained $claude_file; merge it into AGENTS.md first"
  fi
fi

temporary_root=$(mktemp -d "${TMPDIR:-/tmp}/sync-agent-config.XXXXXX")
trap 'rm -rf "$temporary_root"' EXIT

generated_claude="$temporary_root/CLAUDE.md"
agents_stage="$temporary_root/agents-skills"
claude_stage="$temporary_root/claude-skills"
names_file="$temporary_root/skill-names"

mkdir -p "$agents_stage" "$claude_stage"
: >"$names_file"

{
  printf '%s\n\n' "$GENERATED_NOTICE"
  cat "$agents_file"
} >"$generated_claude"

while IFS= read -r -d '' skill_file; do
  skill_directory=${skill_file%/SKILL.md}
  skill_name=${skill_directory##*/}

  case "$skill_name" in
    ''|*[!a-z0-9-]*|-*|*-|*--*)
      die "invalid skill directory name: $skill_directory"
      ;;
  esac
  [ "${#skill_name}" -le 64 ] ||
    die "skill name exceeds 64 characters: $skill_name"

  if grep -Fqx "$skill_name" "$names_file"; then
    die "duplicate skill name: $skill_name"
  fi
  printf '%s\n' "$skill_name" >>"$names_file"

  declared_name=$(
    awk '
      NR == 1 && $0 != "---" { exit }
      NR > 1 && $0 == "---" { exit }
      NR > 1 && $0 ~ /^name:[[:space:]]*/ {
        sub(/^name:[[:space:]]*/, "")
        gsub(/^["\047]|["\047]$/, "")
        print
        exit
      }
    ' "$skill_file"
  )
  [ "$declared_name" = "$skill_name" ] ||
    die "frontmatter name does not match directory: $skill_file"

  source_symlink=$(find "$skill_directory" -type l -print -quit)
  [ -z "$source_symlink" ] ||
    die "skill copies cannot contain symlinks: $source_symlink"

  mkdir "$agents_stage/$skill_name" "$claude_stage/$skill_name"
  cp -R "$skill_directory/." "$agents_stage/$skill_name/"
  cp -R "$skill_directory/." "$claude_stage/$skill_name/"
done < <(find "$skills_root" -type f -name SKILL.md -print0)

printf 'Generated by scripts/sync-agent-config.sh. Edit skills/ and rerun.\n' \
  >"$agents_stage/$GENERATED_MARKER"
printf 'Generated by scripts/sync-agent-config.sh. Edit skills/ and rerun.\n' \
  >"$claude_stage/$GENERATED_MARKER"

if [ "$check_only" -eq 1 ]; then
  status=0
  if ! cmp -s "$generated_claude" "$claude_file"; then
    printf 'stale: CLAUDE.md\n' >&2
    status=1
  fi
  if ! diff -qr "$agents_stage" "$agents_destination" >/dev/null 2>&1; then
    printf 'stale: .agents/skills\n' >&2
    status=1
  fi
  if ! diff -qr "$claude_stage" "$claude_destination" >/dev/null 2>&1; then
    printf 'stale: .claude/skills\n' >&2
    status=1
  fi
  if [ "$status" -ne 0 ]; then
    exit "$status"
  fi
  skill_count=$(wc -l <"$names_file" | tr -d ' ')
  printf 'agent config is synchronized (%s skills)\n' "$skill_count"
  exit 0
fi

deploy_directory() {
  stage=$1
  destination=$2
  parent=${destination%/skills}

  mkdir -p "$parent"
  rm -rf "$destination"
  mv "$stage" "$destination"
  printf 'copied %s\n' "${destination#"$project_root/"}"
}

cp "$generated_claude" "$claude_file"
printf 'updated CLAUDE.md\n'
deploy_directory "$agents_stage" "$agents_destination"
deploy_directory "$claude_stage" "$claude_destination"

skill_count=$(wc -l <"$names_file" | tr -d ' ')
printf 'synchronized %s skills\n' "$skill_count"
